server:
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

spring:
  profiles:
    active: dev # 激活环境配置，dev开发环境，test测试环境，prod生产环境
  datasource:
    type: com.zaxxer.hikari.HikariDataSource    # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException，默认：30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认：30分钟
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000     # 文件上传大小限制为500kb
      max-request-size: 512000  # 请求大小限制为500kb

mybatis:
  type-aliases-package: com.sciatta.openmall.dao.pojo.po          # 所有POJO类所在包路径
  mapper-locations: classpath*:mapper/**/*.xml                        # mapper映射文件

pagehelper: # 分页插件配置
  helperDialect: mysql
  supportMethodsArguments: true